// AUTO-GENERATED by scripts/import-photos.mjs — do not edit by hand.
// Real, user-provided photos for destinations & cities. Captions come from the
// original filenames (reworked); blank caption = generic gallery shot.

export interface Photo {
  /** Path under /public. */
  src: string;
  /** Clean spot name shown UNDER the image (blank for generic gallery shots). */
  caption: string;
}

export const DESTINATION_PHOTOS: Record<string, Photo[]> = {
  "astore": [
    { src: "/photos/destinations/astore/burzil-pass.jpg", caption: "Burzil Pass" },
    { src: "/photos/destinations/astore/deosai-national-park-astore-side.jpg", caption: "Deosai National Park (astore Side)" },
    { src: "/photos/destinations/astore/minimarg.jpg", caption: "Minimarg" },
    { src: "/photos/destinations/astore/rama-lake.jpg", caption: "Rama Lake" },
    { src: "/photos/destinations/astore/rama-meadows.jpg", caption: "Rama Meadows" },
  ],
  "baboonvalley": [
    { src: "/photos/destinations/baboonvalley/baboon-001.jpg", caption: "" },
    { src: "/photos/destinations/baboonvalley/baboon-002.png", caption: "" },
    { src: "/photos/destinations/baboonvalley/baboon-003.jpg", caption: "" },
  ],
  "hunza": [
    { src: "/photos/destinations/hunza/altit-fort.jpg", caption: "Altit Fort" },
    { src: "/photos/destinations/hunza/attabad-lake.jpg", caption: "Attabad Lake" },
    { src: "/photos/destinations/hunza/baltit-fort.jpg", caption: "Baltit Fort" },
    { src: "/photos/destinations/hunza/eagle-s-nest-viewpoint.webp", caption: "Eagle's Nest Viewpoint" },
    { src: "/photos/destinations/hunza/hunza.jpg", caption: "Hunza" },
    { src: "/photos/destinations/hunza/hussaini-suspension-bridge.jpg", caption: "Hussaini Suspension Bridge" },
    { src: "/photos/destinations/hunza/passu-cones.webp", caption: "Passu Cones" },
  ],
  "khaplu": [
    { src: "/photos/destinations/khaplu/khaplu-fort.jpg", caption: "Khaplu Fort" },
    { src: "/photos/destinations/khaplu/khaplu-valley.jpg", caption: "Khaplu Valley" },
    { src: "/photos/destinations/khaplu/manthokha-water-fall.jpg", caption: "Manthokha Water Fall" },
    { src: "/photos/destinations/khaplu/nangma-valley.webp", caption: "Nangma Valley" },
    { src: "/photos/destinations/khaplu/chaqchan-mosque.jpg", caption: "Chaqchan Mosque" },
    { src: "/photos/destinations/khaplu/khafaq-lake.jpg", caption: "Khafaq Lake" },
  ],
  "naltar": [
    { src: "/photos/destinations/naltar/naltor-001.jpg", caption: "" },
    { src: "/photos/destinations/naltar/naltor-002.jpg", caption: "" },
    { src: "/photos/destinations/naltar/naltor-003.jpg", caption: "" },
  ],
  "nooritop": [
    { src: "/photos/destinations/nooritop/noori-top-001.jpg", caption: "" },
    { src: "/photos/destinations/nooritop/noori-top-002.jpg", caption: "" },
    { src: "/photos/destinations/nooritop/noori-top-003.jpg", caption: "" },
  ],
  "raatigali": [
    { src: "/photos/destinations/raatigali/raati-gali-001.jpg", caption: "" },
    { src: "/photos/destinations/raatigali/raati-gali-002.jpg", caption: "" },
    { src: "/photos/destinations/raatigali/raati-gali-003.jpg", caption: "" },
  ],
  "shigar": [
    { src: "/photos/destinations/shigar/blind-lake.jpg", caption: "Blind Lake" },
    { src: "/photos/destinations/shigar/serena-shigar-fort.jpg", caption: "Serena Shigar Fort" },
    { src: "/photos/destinations/shigar/shigar-valley.jpg", caption: "Shigar Valley" },
    { src: "/photos/destinations/shigar/amburiq-mosque.jpg", caption: "Amburiq Mosque" },
    { src: "/photos/destinations/shigar/khilingrong-mosque.jpg", caption: "Khilingrong Mosque" },
  ],
  "skardu": [
    { src: "/photos/destinations/skardu/basho-valley.jpg", caption: "Basho Valley" },
    { src: "/photos/destinations/skardu/chunda-valley.jpg", caption: "Chunda Valley" },
    { src: "/photos/destinations/skardu/doesai-national-park.jpg", caption: "Doesai National Park" },
    { src: "/photos/destinations/skardu/k2-base-camp.jpg", caption: "K2 Base Camp" },
    { src: "/photos/destinations/skardu/katpana-desert.jpg", caption: "Katpana Desert" },
    { src: "/photos/destinations/skardu/katpana-lake.jpg", caption: "Katpana Lake" },
    { src: "/photos/destinations/skardu/kharphocho-fort.jpg", caption: "Kharphocho Fort" },
    { src: "/photos/destinations/skardu/satpara-lake.jpg", caption: "Satpara Lake" },
    { src: "/photos/destinations/skardu/shangrila-lower-kachura-lake.jpg", caption: "Shangrila Lower Kachura Lake" },
    { src: "/photos/destinations/skardu/shausar-lake.jpg", caption: "Shausar Lake" },
    { src: "/photos/destinations/skardu/shoq-valley.webp", caption: "Shoq Valley" },
    { src: "/photos/destinations/skardu/upper-kachura-lake.jpg", caption: "Upper Kachura Lake" },
  ],
};

export const CITY_PHOTOS: Record<string, Photo[]> = {
  "ahmadpureast": [
    { src: "/photos/cities/ahmadpureast/derawar-fort.jpg", caption: "Derawar Fort" },
    { src: "/photos/cities/ahmadpureast/sadiq-garh-mosque.jpg", caption: "Sadiq Garh Mosque" },
    { src: "/photos/cities/ahmadpureast/sadiq-garh-palace.jpg", caption: "Sadiq Garh Palace" },
  ],
  "attock": [
    { src: "/photos/cities/attock/attock-bridge.jpg", caption: "Attock Bridge" },
    { src: "/photos/cities/attock/attock-fort.jpg", caption: "Attock Fort" },
    { src: "/photos/cities/attock/bagh-neelab.webp", caption: "Bagh Neelab" },
    { src: "/photos/cities/attock/khairabad-park.jpg", caption: "Khairabad Park" },
  ],
  "bahawalnagar": [
    { src: "/photos/cities/bahawalnagar/bahawalnagar-wildlife-park.jpg", caption: "Bahawalnagar Wildlife Park" },
    { src: "/photos/cities/bahawalnagar/marot-fort.webp", caption: "Marot Fort" },
    { src: "/photos/cities/bahawalnagar/sutlej-river-banks.jpg", caption: "Sutlej River Banks" },
  ],
  "bahawalpur": [
    { src: "/photos/cities/bahawalpur/bahawalpur-museum.webp", caption: "Bahawalpur Museum" },
    { src: "/photos/cities/bahawalpur/darbar-mahal.jpg", caption: "Darbar Mahal" },
    { src: "/photos/cities/bahawalpur/derawar-fort.jpg", caption: "Derawar Fort" },
    { src: "/photos/cities/bahawalpur/lal-suhanra-national-park.webp", caption: "Lal Suhanra National Park" },
    { src: "/photos/cities/bahawalpur/noor-mahal.jpg", caption: "Noor Mahal" },
  ],
  "bhakkar": [
    { src: "/photos/cities/bhakkar/darbar-shah-sulaiman.webp", caption: "Darbar Shah Sulaiman" },
    { src: "/photos/cities/bhakkar/indus-river-bank.jpg", caption: "Indus River Bank" },
    { src: "/photos/cities/bhakkar/mankera-fort.jpg", caption: "Mankera Fort" },
    { src: "/photos/cities/bhakkar/thal-desert.jpg", caption: "Thal Desert" },
  ],
  "burewala": [
    { src: "/photos/cities/burewala/burewala-cricket-stadium.jpg", caption: "Burewala Cricket Stadium" },
    { src: "/photos/cities/burewala/fawara-chowk.jpg", caption: "Fawara Chowk" },
    { src: "/photos/cities/burewala/shrine-of-baba-haji-sher-muhammad-qalandar.jpg", caption: "Shrine Of Baba Haji Sher Muhammad Qalandar" },
  ],
  "chakwal": [
    { src: "/photos/cities/chakwal/kallar-kahar-lake.jpg", caption: "Kallar Kahar Lake" },
    { src: "/photos/cities/chakwal/katas-raj-temples.jpg", caption: "Katas Raj Temples" },
    { src: "/photos/cities/chakwal/khewra-salt-mine.jpg", caption: "Khewra Salt Mine" },
    { src: "/photos/cities/chakwal/shrine-of-sultan-bahu.jpg", caption: "Shrine Of Sultan Bahu" },
  ],
  "chichawatni": [
    { src: "/photos/cities/chichawatni/chichawatni-forest.jpg", caption: "Chichawatni Forest" },
    { src: "/photos/cities/chichawatni/harappa-archaeological-site.jpg", caption: "Harappa Archaeological Site" },
    { src: "/photos/cities/chichawatni/harappa-museum.jpg", caption: "Harappa Museum" },
  ],
  "chiniot": [
    { src: "/photos/cities/chiniot/bahishti-maqbara.jpg", caption: "Bahishti Maqbara" },
    { src: "/photos/cities/chiniot/chennab-river.jpg", caption: "Chennab River" },
    { src: "/photos/cities/chiniot/omar-hayat-mahal.jpg", caption: "Omar Hayat Mahal" },
    { src: "/photos/cities/chiniot/shahi-mosque.jpg", caption: "Shahi Mosque" },
  ],
  "chishtian": [
    { src: "/photos/cities/chishtian/chishtian-lake.jpg", caption: "Chishtian Lake" },
    { src: "/photos/cities/chishtian/jamia-mosque.jpg", caption: "Jamia Mosque" },
    { src: "/photos/cities/chishtian/shrine-of-taj-sarwar-chishti.jpg", caption: "Shrine Of Taj Sarwar Chishti" },
  ],
  "daska": [
    { src: "/photos/cities/daska/daska-fort-kot-daska.jpg", caption: "Daska Fort (kot Daska)" },
    { src: "/photos/cities/daska/shahab-masjid.jpg", caption: "Shahab Masjid" },
    { src: "/photos/cities/daska/shaheedan-wala-qabrastan.jpg", caption: "Shaheedan Wala Qabrastan" },
  ],
  "dgkhan": [
    { src: "/photos/cities/dgkhan/dg-khan-museum.jpg", caption: "DG Khan Museum" },
    { src: "/photos/cities/dgkhan/dg-khan-zoo.jpg", caption: "DG Khan Zoo" },
    { src: "/photos/cities/dgkhan/fort-munro.jpg", caption: "Fort Munro" },
    { src: "/photos/cities/dgkhan/tomb-of-ghazi-khan.jpg", caption: "Tomb Of Ghazi Khan" },
    { src: "/photos/cities/dgkhan/tomb-of-sakhi-sarwar.jpg", caption: "Tomb Of Sakhi Sarwar" },
  ],
  "faisalabad": [
    { src: "/photos/cities/faisalabad/eight-bazaars.jpg", caption: "Eight Bazaars" },
    { src: "/photos/cities/faisalabad/gatwala-wildlife-park.jpg", caption: "Gatwala Wildlife Park" },
    { src: "/photos/cities/faisalabad/ghanta-ghar-faisalabad.jpg", caption: "Ghanta Ghar Faisalabad" },
    { src: "/photos/cities/faisalabad/jinnah-garden-company-bag.jpg", caption: "Jinnah Garden (company Bag)" },
    { src: "/photos/cities/faisalabad/lyallpur-museum.png", caption: "Lyallpur Museum" },
  ],
  "gojra": [
    { src: "/photos/cities/gojra/gojra-grain-market.jpg", caption: "Gojra Grain Market" },
    { src: "/photos/cities/gojra/manzoor-elahi-forest-park.jpg", caption: "Manzoor Elahi Forest Park" },
  ],
  "gujranwala": [
    { src: "/photos/cities/gujranwala/gurdwara-rori-sahib-eminabad.jpg", caption: "Gurdwara Rori Sahib, Eminabad" },
    { src: "/photos/cities/gujranwala/haveli-ranjit-singh.jpg", caption: "Haveli Ranjit Singh" },
    { src: "/photos/cities/gujranwala/jinnah-stadium-parks.jpg", caption: "Jinnah Stadium Parks" },
    { src: "/photos/cities/gujranwala/sheranwala-bagh-company-bagh.jpg", caption: "Sheranwala Bagh (company Bagh)" },
    { src: "/photos/cities/gujranwala/sheranwala-gate.jpg", caption: "Sheranwala Gate" },
  ],
  "gujrat": [
    { src: "/photos/cities/gujrat/gujrat-fort.jpg", caption: "Gujrat Fort" },
    { src: "/photos/cities/gujrat/gujrat-pottery-bazaar.jpg", caption: "Gujrat Pottery Bazaar" },
    { src: "/photos/cities/gujrat/mangla-dam-fort.jpg", caption: "Mangla Dam & Fort" },
    { src: "/photos/cities/gujrat/shrine-of-hazrat-shah-daula.jpg", caption: "Shrine Of Hazrat Shah Daula" },
  ],
  "hafizabad": [
    { src: "/photos/cities/hafizabad/chenab-river-bank.webp", caption: "Chenab River Bank" },
    { src: "/photos/cities/hafizabad/family-park.jpg", caption: "Family Park" },
    { src: "/photos/cities/hafizabad/hafizabad-museum.jpg", caption: "Hafizabad Museum" },
    { src: "/photos/cities/hafizabad/akbari-gate.jpg", caption: "Akbari Gate" },
  ],
  "jaranwala": [
    { src: "/photos/cities/jaranwala/committee-bagh.jpg", caption: "Committee Bagh" },
    { src: "/photos/cities/jaranwala/mahtab-masjid.jpg", caption: "Mahtab Masjid" },
    { src: "/photos/cities/jaranwala/pakistani-gate.jpg", caption: "Pakistani Gate" },
  ],
  "jhang": [
    { src: "/photos/cities/jhang/shrine-of-sultan-bahu-garh-maharaja.jpg", caption: "Shrine Of Sultan Bahu, Garh Maharaja" },
    { src: "/photos/cities/jhang/tomb-of-heer-ranjha.jpg", caption: "Tomb Of Heer Ranjha" },
    { src: "/photos/cities/jhang/trimmu-barrage.jpg", caption: "Trimmu Barrage" },
  ],
  "jhelum": [
    { src: "/photos/cities/jhelum/mangla-dam.jpg", caption: "Mangla Dam" },
    { src: "/photos/cities/jhelum/rasul-barrage.jpg", caption: "Rasul Barrage" },
    { src: "/photos/cities/jhelum/rohtas-fort.jpg", caption: "Rohtas Fort" },
    { src: "/photos/cities/jhelum/tilla-jogian.jpg", caption: "Tilla Jogian" },
  ],
  "kamalia": [
    { src: "/photos/cities/kamalia/jahangir-era-mosque.webp", caption: "Jahangir Era Mosque" },
    { src: "/photos/cities/kamalia/kamalia-wildlife-park.jpg", caption: "Kamalia Wildlife Park" },
    { src: "/photos/cities/kamalia/shrine-of-baba-fazil-dewan.jpg", caption: "Shrine Of Baba Fazil Dewan" },
  ],
  "kamoke": [
    { src: "/photos/cities/kamoke/kamoke-rice-market.jpg", caption: "Kamoke Rice Market" },
    { src: "/photos/cities/kamoke/grand-trunk-road-kamoke.jpg", caption: "Grand Trunk Road Kamoke" },
  ],
  "kasur": [
    { src: "/photos/cities/kasur/changa-manga-forest.jpg", caption: "Changa Manga Forest" },
    { src: "/photos/cities/kasur/ganda-singh-border.jpg", caption: "Ganda Singh Border" },
    { src: "/photos/cities/kasur/mazar-of-baba-kamal-chishti.jpg", caption: "Mazar Of Baba Kamal Chishti" },
    { src: "/photos/cities/kasur/shrine-of-baba-bulleh-shah.jpg", caption: "Shrine Of Baba Bulleh Shah" },
  ],
  "khanewal": [
    { src: "/photos/cities/khanewal/khanewal-junction.jpg", caption: "Khanewal Junction" },
    { src: "/photos/cities/khanewal/ruins-of-tulamba.webp", caption: "Ruins Of Tulamba" },
    { src: "/photos/cities/khanewal/sher-shah-suri-fort-tulamba.jpg", caption: "Sher Shah Suri Fort, Tulamba" },
    { src: "/photos/cities/khanewal/shrine-of-khalid-walid.jpg", caption: "Shrine Of Khalid Walid" },
  ],
  "khanpur": [
    { src: "/photos/cities/khanpur/cholistan-desert.jpg", caption: "Cholistan Desert" },
    { src: "/photos/cities/khanpur/khanqah-e-aaliya-qadriya.jpg", caption: "Khanqah E Aaliya Qadriya" },
    { src: "/photos/cities/khanpur/patan-minara.jpg", caption: "Patan Minara" },
  ],
  "khushab": [
    { src: "/photos/cities/khushab/kanhatti-garden.webp", caption: "Kanhatti Garden" },
    { src: "/photos/cities/khushab/soon-valley.jpg", caption: "Soon Valley" },
    { src: "/photos/cities/khushab/uchhali-lake.jpg", caption: "Uchhali Lake" },
  ],
  "kotadu": [
    { src: "/photos/cities/kotadu/bagh-e-sardaran.jpg", caption: "Bagh E Sardaran" },
    { src: "/photos/cities/kotadu/indus-river-bank.jpg", caption: "Indus River Bank" },
    { src: "/photos/cities/kotadu/taunsa-barrage.jpg", caption: "Taunsa Barrage" },
  ],
  "lahore": [
    { src: "/photos/cities/lahore/badshahi-mosque.jpg", caption: "Badshahi Mosque" },
    { src: "/photos/cities/lahore/lahore-fort.jpg", caption: "Lahore Fort" },
    { src: "/photos/cities/lahore/lahore-museum.jpg", caption: "Lahore Museum" },
    { src: "/photos/cities/lahore/minar-e-pakistan.jpg", caption: "Minar E Pakistan" },
    { src: "/photos/cities/lahore/shalimar-gardens.jpg", caption: "Shalimar Gardens" },
    { src: "/photos/cities/lahore/wazir-khan-mosque.webp", caption: "Wazir Khan Mosque" },
  ],
  "mandibahauddin": [
    { src: "/photos/cities/mandibahauddin/chillianwala-battlefield.jpg", caption: "Chillianwala Battlefield" },
    { src: "/photos/cities/mandibahauddin/gurdwara-chak-mai-daas.jpg", caption: "Gurdwara Chak Mai Daas" },
    { src: "/photos/cities/mandibahauddin/mandi-bahauddin-bazaar.jpg", caption: "Mandi Bahauddin Bazaar" },
    { src: "/photos/cities/mandibahauddin/qadirabad-barrage.jpg", caption: "Qadirabad Barrage" },
    { src: "/photos/cities/mandibahauddin/rasul-barrage.jpg", caption: "Rasul Barrage" },
  ],
  "mianwali": [
    { src: "/photos/cities/mianwali/chashma-barrage.jpg", caption: "Chashma Barrage" },
    { src: "/photos/cities/mianwali/kalabagh.jpg", caption: "Kalabagh" },
    { src: "/photos/cities/mianwali/namal-lake.png", caption: "Namal Lake" },
    { src: "/photos/cities/mianwali/thal-desert.webp", caption: "Thal Desert" },
  ],
  "multan": [
    { src: "/photos/cities/multan/delhi-gate.jpg", caption: "Delhi Gate" },
    { src: "/photos/cities/multan/hussain-agahi-bazaar.jpg", caption: "Hussain Agahi Bazaar" },
    { src: "/photos/cities/multan/multan-fort-qila-kohna.jpg", caption: "Multan Fort (qila Kohna)" },
    { src: "/photos/cities/multan/multan-museum.jpg", caption: "Multan Museum" },
    { src: "/photos/cities/multan/shrine-of-bahauddin-zakariya.jpg", caption: "Shrine Of Bahauddin Zakariya" },
    { src: "/photos/cities/multan/tomb-of-shah-rukn-e-alam.webp", caption: "Tomb Of Shah Rukn E Alam" },
  ],
  "muzaffargarh": [
    { src: "/photos/cities/muzaffargarh/fort-kohna.jpg", caption: "Fort Kohna" },
    { src: "/photos/cities/muzaffargarh/sher-shah-park.jpg", caption: "Sher Shah Park" },
    { src: "/photos/cities/muzaffargarh/shrine-of-sheikh-sadan-shaheed.jpg", caption: "Shrine Of Sheikh Sadan Shaheed" },
    { src: "/photos/cities/muzaffargarh/taunsa-barrage.jpg", caption: "Taunsa Barrage" },
  ],
  "narowal": [
    { src: "/photos/cities/narowal/baba-guru-nanak-fields.jpg", caption: "Baba Guru Nanak Fields" },
    { src: "/photos/cities/narowal/gurdwara-darbar-sahib-kartarpur.jpg", caption: "Gurdwara Darbar Sahib Kartarpur" },
    { src: "/photos/cities/narowal/kartarpur-corridor.jpg", caption: "Kartarpur Corridor" },
    { src: "/photos/cities/narowal/shakargarh.jpg", caption: "Shakargarh" },
  ],
  "okara": [
    { src: "/photos/cities/okara/aashiq-park.jpg", caption: "Aashiq Park" },
    { src: "/photos/cities/okara/farid-ud-din-water-park.jpg", caption: "Farid Ud Din Water Park" },
    { src: "/photos/cities/okara/kharal-lake.png", caption: "Kharal Lake" },
    { src: "/photos/cities/okara/safdar-shaheed-park-company-bagh.webp", caption: "Safdar Shaheed Park (company Bagh)" },
  ],
  "pakpattan": [
    { src: "/photos/cities/pakpattan/chan-pir-darbar.jpg", caption: "Chan Pir Darbar" },
    { src: "/photos/cities/pakpattan/malka-hans.jpg", caption: "Malka Hans" },
    { src: "/photos/cities/pakpattan/shrine-of-baba-farid-ganjshakar.jpg", caption: "Shrine Of Baba Farid Ganjshakar" },
  ],
  "rahimyarkhan": [
    { src: "/photos/cities/rahimyarkhan/bhong-mosque.jpg", caption: "Bhong Mosque" },
    { src: "/photos/cities/rahimyarkhan/cholistan-desert.jpg", caption: "Cholistan Desert" },
    { src: "/photos/cities/rahimyarkhan/pattan-minar.jpg", caption: "Pattan Minar" },
    { src: "/photos/cities/rahimyarkhan/sadiq-garh-palace.jpg", caption: "Sadiq Garh Palace" },
  ],
  "rawalpindi": [
    { src: "/photos/cities/rawalpindi/ayub-national-park.jpg", caption: "Ayub National Park" },
    { src: "/photos/cities/rawalpindi/mall-of-rawalpindi-in-saddar-bazaar.png", caption: "Mall Of Rawalpindi In Saddar Bazaar" },
    { src: "/photos/cities/rawalpindi/pakistan-army-museum.jpg", caption: "Pakistan Army Museum" },
    { src: "/photos/cities/rawalpindi/raja-bazaar.jpg", caption: "Raja Bazaar" },
    { src: "/photos/cities/rawalpindi/rawalpindi-museum.jpg", caption: "Rawalpindi Museum" },
  ],
  "sadiqabad": [
    { src: "/photos/cities/sadiqabad/bhong-mosque.jpg", caption: "Bhong Mosque" },
    { src: "/photos/cities/sadiqabad/cholistan-desert.jpg", caption: "Cholistan Desert" },
  ],
  "sahiwal": [
    { src: "/photos/cities/sahiwal/company-bagh.jpg", caption: "Company Bagh" },
    { src: "/photos/cities/sahiwal/harappa-archaeological-site.jpg", caption: "Harappa Archaeological Site" },
    { src: "/photos/cities/sahiwal/harappa-museum.jpg", caption: "Harappa Museum" },
    { src: "/photos/cities/sahiwal/kanaan-park.jpg", caption: "Kanaan Park" },
    { src: "/photos/cities/sahiwal/yadgar-movement.webp", caption: "Yadgar Movement" },
  ],
  "sargodha": [
    { src: "/photos/cities/sargodha/company-bagh.jpg", caption: "Company Bagh" },
    { src: "/photos/cities/sargodha/jahaz-bara-picnic-spot.jpg", caption: "Jahaz Bara Picnic Spot" },
    { src: "/photos/cities/sargodha/kirana-hills.jpg", caption: "Kirana Hills" },
    { src: "/photos/cities/sargodha/sher-shah-suri-mosque-bhera.jpg", caption: "Sher Shah Suri Mosque, Bhera" },
  ],
  "sheikhupura": [
    { src: "/photos/cities/sheikhupura/area-wetlands.jpg", caption: "Area Wetlands" },
    { src: "/photos/cities/sheikhupura/hiran-minar.jpg", caption: "Hiran Minar" },
    { src: "/photos/cities/sheikhupura/sheikhupura-fort.jpg", caption: "Sheikhupura Fort" },
    { src: "/photos/cities/sheikhupura/tomb-of-waris-shah-jandiala-sher-khan.jpg", caption: "Tomb Of Waris Shah, Jandiala Sher Khan" },
  ],
  "sialkot": [
    { src: "/photos/cities/sialkot/allama-iqbal-manzil.jpg", caption: "Allama Iqbal Manzil" },
    { src: "/photos/cities/sialkot/gurdwara-beri-sahib.jpg", caption: "Gurdwara Beri Sahib" },
    { src: "/photos/cities/sialkot/holy-trinity-cathedral.jpg", caption: "Holy Trinity Cathedral" },
    { src: "/photos/cities/sialkot/marala-headworks.jpg", caption: "Marala Headworks" },
    { src: "/photos/cities/sialkot/sialkot-fort.jpg", caption: "Sialkot Fort" },
  ],
  "tobateksingh": [
    { src: "/photos/cities/tobateksingh/darbar-e-qutbia.jpg", caption: "Darbar E Qutbia" },
    { src: "/photos/cities/tobateksingh/kamalia-wildlife-park.jpg", caption: "Kamalia Wildlife Park" },
    { src: "/photos/cities/tobateksingh/manzoor-elahi-forest-park.jpg", caption: "Manzoor Elahi Forest Park" },
    { src: "/photos/cities/tobateksingh/teko-park.jpg", caption: "Teko Park" },
  ],
  "vehari": [
    { src: "/photos/cities/vehari/bagh-wali-mosque.jpg", caption: "Bagh Wali Mosque" },
    { src: "/photos/cities/vehari/mailsi-siphon.jpg", caption: "Mailsi Siphon" },
    { src: "/photos/cities/vehari/sutlej-river-bank.jpg", caption: "Sutlej River Bank" },
  ],
  "wahcantt": [
    { src: "/photos/cities/wahcantt/gurdwara-panja-sahib.jpg", caption: "Gurdwara Panja Sahib" },
    { src: "/photos/cities/wahcantt/tomb-of-lala-rukh.jpg", caption: "Tomb Of Lala Rukh" },
    { src: "/photos/cities/wahcantt/wah-gardens.jpg", caption: "Wah Gardens" },
  ],
  "wazirabad": [
    { src: "/photos/cities/wazirabad/chenab-river-bridge.webp", caption: "Chenab River Bridge" },
    { src: "/photos/cities/wazirabad/qila-wazirabad.webp", caption: "Qila Wazirabad" },
    { src: "/photos/cities/wazirabad/wazir-khan-baradari.jpg", caption: "Wazir Khan Baradari" },
  ],
};

export function destPhotos(id: string): Photo[] {
  return DESTINATION_PHOTOS[id] ?? [];
}

export function cityPhotos(id: string): Photo[] {
  return CITY_PHOTOS[id] ?? [];
}

/** First real photo for a place, used as the hero when available. */
export function destHero(id: string): string | undefined {
  return DESTINATION_PHOTOS[id]?.[0]?.src;
}

export function cityHero(id: string): string | undefined {
  return CITY_PHOTOS[id]?.[0]?.src;
}
